document.addEventListener('DOMContentLoaded',function () {
  bindCity('ALL');
});

let takeToken = document.querySelector('.execphpwidget').innerText;
let accessToken = JSON.parse(takeToken).AccessGatewayResponse.TokenInfo[0].AccessToken;
let siteEncoded = encodeURIComponent('https://www.nationalboilerparts.co.uk/design-new-ilya-test/');
let AccessTokenEncoded = encodeURIComponent(accessToken);


function bindCity(letterValue) {
  blockCityList.innerHTML = '';
  let cityListFilter = [];
  for (let i = 0; i < cityList.length; i++) {
    if (letterValue == "ALL" || cityList[i].title[0] == letterValue) {
      cityListFilter += `<a class = blockCityList-cell title='${cityList[i].title}' href = 'https://www.ups.com/aplp/invoke?cburl=${siteEncoded}&oId=qwerty1234&city=${cityList[i].title}&searchCountry=GB&displayLanguage=en&countrySite=GB&viewPortResponsive=true&accessToken=${AccessTokenEncoded}'>${cityList[i].title}</a>`;
    }else if(letterValue == 'X' || letterValue == 'Z' ){
      cityListFilter += `<div class = blockCityList-noResults>No results</div>`;
      break;
    }
  }
  blockCityList.innerHTML += cityListFilter;
}

let blockCityList = document.querySelector('.blockCityList');
let letter = document.querySelectorAll('.alphabet-letter');
for (let i = 0; i < letter.length; i++) {
  letter[i].onclick = function (event) {
    let letterValue = event.target.innerText;
    bindCity(letterValue);
  }
}

let cityList = [
  {title: "Abbey Wood", postal:"SE2"},
  {title: "Aberdare", postal:"CF44"},
  {title: "Aberdeen", postal:" "},
  {title: "Abergavenny", postal:" "},
  {title: "Abertillery", postal:" "},
  {title: "Aberystwyth", postal:" "},
  {title: "Abingdon", postal:" "},
  {title: "Accrington", postal:" "},
  {title: "Acton", postal:" "},
  {title: "Adderbury", postal:" "},
  {title: "Addington", postal:" "},
  {title: "Addlestone", postal:" "},
  {title: "Adlington", postal:" "},
  {title: "Aigburth", postal:" "},
  {title: "Airdale", postal:" "},
  {title: "Airdrie", postal:" "},
  {title: "Albrighton", postal:" "},
  {title: "Alcester", postal:" "},
  {title: "Alconbury", postal:" "},
  {title: "Aldermaston", postal:" "},
  {title: "Aldershot", postal:" "},
  {title: "Aldridge", postal:" "},
  {title: "Alexandra Palace and Wood Green", postal:" "},
  {title: "Alexandria", postal:" "},
  {title: "Alford", postal:" "},
  {title: "Allestree", postal:" "},
  {title: "Allington", postal:" "},
  {title: "Alloa", postal:" "},
  {title: "Almondbank", postal:" "},
  {title: "Alnwick", postal:" "},
  {title: "Alridge", postal:" "},
  {title: "Altofts", postal:" "},
  {title: "Alton", postal:" "},
  {title: "Altrincham", postal:" "},
  {title: "Alva", postal:" "},
  {title: "Alvaston", postal:" "},
  {title: "Alverthorpe", postal:" "},
  {title: "Amble", postal:" "},
  {title: "Amersham", postal:" "},
  {title: "Ammanford", postal:" "},
  {title: "Ampthill", postal:" "},
  {title: "Andover", postal:" "},
  {title: "Annan", postal:" "},
  {title: "Anstey", postal:" "},
  {title: "Antrim", postal:" "},
  {title: "Appleton", postal:" "},
  {title: "Apsley", postal:" "},
  {title: "Arbroath", postal:" "},
  {title: "Archway and Tufnell Park", postal:" "},
  {title: "Armthorpe", postal:" "},
  {title: "Arrowe Park", postal:" "},
  {title: "Asbourne", postal:" "},
  {title: "Ash", postal:" "},
  {title: "Ashburton", postal:" "},
  {title: "Ashby De La Zouch", postal:" "},
  {title: "Ashford", postal:" "},
  {title: "Ashington", postal:" "},
  {title: "Ashton In Makerfield", postal:" "},
  {title: "Ashton Under Lyne", postal:" "},
  {title: "Ashton-In-Makerfield", postal:" "},
  {title: "Ashurst Wood", postal:" "},
  {title: "Astley", postal:" "},
  {title: "Aston, Sheffield", postal:" "},
  {title: "Atherton", postal:" "},
  {title: "Attleborough", postal:" "},
  {title: "Auchtermuchty", postal:" "},
  {title: "Audlem", postal:" "},
  {title: "Axbridge", postal:" "},
  {title: "Aylesbury", postal:" "},
  {title: "Aylesford", postal:" "},
  {title: "Aylesham", postal:" "},
  {title: "Aylestone", postal:" "},
  {title: "Aylsham", postal:" "},
  {title: "Ayr", postal:" "},
  {title: "Backwell", postal:" "},
  {title: "Bacup", postal:" "},
  {title: "Baildon", postal:" "},
  {title: "Bakewell", postal:" "},
  {title: "Baldock", postal:" "},
  {title: "Balham", postal:" "},
  {title: "Ballyclare", postal:" "},
  {title: "Ballygowan", postal:" "},
  {title: "Ballymena", postal:" "},
  {title: "Ballynahinch", postal:" "},
  {title: "Bamber Bridge", postal:" "},
  {title: "Banbridge", postal:" "},
  {title: "Banbury", postal:" "},
  {title: "Banchory", postal:" "},
  {title: "Bangor", postal:" "},
  {title: "Bannockburn", postal:" "},
  {title: "Banstead", postal:" "},
  {title: "Bardford", postal:" "},
  {title: "Bargoed", postal:" "},
  {title: "Barking", postal:" "},
  {title: "Barkingside", postal:" "},
  {title: "Barnard Castle", postal:" "},
  {title: "Barnes and Castelnau", postal:" "},
  {title: "Barnet", postal:" "},
  {title: "Barnham", postal:" "},
  {title: "Barnoldswick", postal:" "},
  {title: "Barnsbury, Canonbury and Islington", postal:" "},
  {title: "Barnsley", postal:" "},
  {title: "Barnstaple", postal:" "},
  {title: "Barrhead", postal:" "},
  {title: "Barrow In Furness", postal:" "},
  {title: "Barry", postal:" "},
  {title: "Barton Upon Humber", postal:" "},
  {title: "Barton-Under-Needwood", postal:" "},
  {title: "Barwell", postal:" "},
  {title: "Basildon", postal:" "},
  {title: "Basingstoke", postal:" "},
  {title: "Bath", postal:" "},
  {title: "Bathgate", postal:" "},
  {title: "Batley", postal:" "},
  {title: "Battersea", postal:" "},
  {title: "Battersea and Clapham Junction", postal:" "},
  {title: "Battle", postal:" "},
  {title: "Battlesbridge", postal:" "},
  {title: "Bayswater and Paddington", postal:" "},
  {title: "Beaddu", postal:" "},
  {title: "Bearsden", postal:" "},
  {title: "Beaulieu", postal:" "},
  {title: "Bebington", postal:" "},
  {title: "Beccles", postal:" "},
  {title: "Beck Row", postal:" "},
  {title: "Beckenham", postal:" "},
  {title: "Bedale", postal:" "},
  {title: "Beddau", postal:" "},
  {title: "Bedford", postal:" "},
  {title: "Bedlington", postal:" "},
  {title: "Bedmond", postal:" "},
  {title: "Bedwas-Caerphilly", postal:" "},
  {title: "Bedworth", postal:" "},
  {title: "Beeston", postal:" "},
  {title: "Belfast", postal:" "},
  {title: "Belle Vale", postal:" "},
  {title: "Bellingham", postal:" "},
  {title: "Bellingham, Catford and Hither Green", postal:" "},
  {title: "Bellshill", postal:" "},
  {title: "Belper", postal:" "},
  {title: "Belvedere", postal:" "},
  {title: "Benfleet", postal:" "},
  {title: "Bengeo", postal:" "},
  {title: "Bentham", postal:" "},
  {title: "Benton", postal:" "},
  {title: "Berinsfield", postal:" "},
  {title: "Berkhamsted", postal:" "},
  {title: "Bermondsey", postal:" "},
  {title: "Bermondsey, Borough, Southwark and Waterloo", postal:" "},
  {title: "Berwick", postal:" "},
  {title: "Bethnal Green and Shoreditch", postal:" "},
  {title: "Bewdley", postal:" "},
  {title: "Bexhill", postal:" "},
  {title: "Bexley", postal:" "},
  {title: "Bexleyheath", postal:" "},
  {title: "Bicester", postal:" "},
  {title: "Bideford", postal:" "},
  {title: "Biggleswade", postal:" "},
  {title: "Bilbrook", postal:" "},
  {title: "Billericay", postal:" "},
  {title: "Billingham", postal:" "},
  {title: "Billinghurst", postal:" "},
  {title: "Billingshurst", postal:" "},
  {title: "Bilston", postal:" "},
  {title: "Bingley", postal:" "},
  {title: "Birchington", postal:" "},
  {title: "Bircotes", postal:" "},
  {title: "Birkby", postal:" "},
  {title: "Birkenhead", postal:" "},
  {title: "Birmingham", postal:" "},
  {title: "Birstall", postal:" "},
  {title: "Bishop Auckland", postal:" "},
  {title: "Bishops Stortford", postal:" "},
  {title: "Bishops Waltham", postal:" "},
  {title: "Bishopton", postal:" "},
  {title: "Bispham", postal:" "},
  {title: "Blackburn", postal:" "},
  {title: "Blackheath", postal:" "},
  {title: "Blackheath and Westcombe Park", postal:" "},
  {title: "Blackpool", postal:" "},
  {title: "Blackwell", postal:" "},
  {title: "Blairgowrie", postal:" "},
  {title: "Blandford Forum", postal:" "},
  {title: "Blantyre", postal:" "},
  {title: "Bletchley", postal:" "},
  {title: "Blewbury", postal:" "},
  {title: "Blofield", postal:" "},
  {title: "Blyth", postal:" "},
  {title: "Bodmin", postal:" "},
  {title: "Bognor Regis", postal:" "},
  {title: "Boldon Colliery", postal:" "},
  {title: "Bolton", postal:" "},
  {title: "Bow and Bromley-by-Bow", postal:" "},
  {title: "Brent Cross and Hendon", postal:" "},
  {title: "Brixton and Stockwell", postal:" "},
  {title: "Brixton and Streatham Hill", postal:" "},
  {title: "Brockley, Crofton Park and Honor Oak Park", postal:" "},
  {title: "Bromley", postal:" "},
  {title: "Camberwell", postal:" "},
  {title: "Camden Town and Regent's Park", postal:" "},
  {title: "Canning Town and North Woolwich", postal:" "},
  {title: "Charlton", postal:" "},
  {title: "Chingford and Highams Park", postal:" "},
  {title: "Chiswick", postal:" "},
  {title: "Clapton", postal:" "},
  {title: "Colindale and Kingsbury", postal:" "},
  {title: "Colnbrook", postal:" "},
  {title: "Colne", postal:" "},
  {title: "Coltishall", postal:" "},
  {title: "Colwyn Bay", postal:" "},
  {title: "Congleton", postal:" "},
  {title: "Conisbrough", postal:" "},
  {title: "Conlig", postal:" "},
  {title: "Connahs Quay", postal:" "},
  {title: "Consett", postal:" "},
  {title: "Conway", postal:" "},
  {title: "Cookstown", postal:" "},
  {title: "Copley", postal:" "},
  {title: "Corby", postal:" "},
  {title: "Corsham", postal:" "},
  {title: "Cosford", postal:" "},
  {title: "Cosham", postal:" "},
  {title: "Cotebrook", postal:" "},
  {title: "Cottesmore", postal:" "},
  {title: "Cottingham", postal:" "},
  {title: "Coulsdon", postal:" "},
  {title: "Coventry", postal:" "},
  {title: "Cowbridge", postal:" "},
  {title: "Cowdenbeath", postal:" "},
  {title: "Cowes", postal:" "},
  {title: "Cowplain", postal:" "},
  {title: "Cradley Heath", postal:" "},
  {title: "Crail", postal:" "},
  {title: "Cramlington", postal:" "},
  {title: "Cranbrook", postal:" "},
  {title: "Cranfield", postal:" "},
  {title: "Cranham", postal:" "},
  {title: "Cranleigh", postal:" "},
  {title: "Crawley", postal:" "},
  {title: "Crayford", postal:" "},
  {title: "Crediton", postal:" "},
  {title: "Crewe", postal:" "},
  {title: "Crewkerne", postal:" "},
  {title: "Cricklade", postal:" "},
  {title: "Cricklewood and Neasden", postal:" "},
  {title: "Croespenmaen", postal:" "},
  {title: "Crofton", postal:" "},
  {title: "Cromer", postal:" "},
  {title: "Crook", postal:" "},
  {title: "Crosby", postal:" "},
  {title: "Crouch End and Hornsey", postal:" "},
  {title: "Crowborough", postal:" "},
  {title: "Crowthorne", postal:" "},
  {title: "Croxley Green", postal:" "},
  {title: "Croydon", postal:" "},
  {title: "Crystal Palace and Upper Norwood", postal:" "},
  {title: "Cuckfield", postal:" "},
  {title: "Cudworth", postal:" "},
  {title: "Culcheth", postal:" "},
  {title: "Cullingworth", postal:" "},
  {title: "Cumbernauld", postal:" "},
  {title: "Cupar", postal:" "},
  {title: "Currie", postal:" "},
  {title: "Cwmbran", postal:" "},
  {title: "Cwmparc", postal:" "},
  {title: "Dagenham", postal:" "},
  {title: "Dalbeattie", postal:" "},
  {title: "Dalton-In-Furness", postal:" "},
  {title: "Danbury", postal:" "},
  {title: "Darlington", postal:" "},
  {title: "Dartford", postal:" "},
  {title: "Darwen", postal:" "},
  {title: "Datchet", postal:" "},
  {title: "Daventry", postal:" "},
  {title: "Dawlish", postal:" "},
  {title: "Deal", postal:" "},
  {title: "Denbigh", postal:" "},
  {title: "Denny", postal:" "},
  {title: "Denton", postal:" "},
  {title: "Deptford", postal:" "},
  {title: "Derby", postal:" "},
  {title: "Derbyshire", postal:" "},
  {title: "Dereham", postal:" "},
  {title: "Devizes", postal:" "},
  {title: "Dewsbury", postal:" "},
  {title: "Didcot", postal:" "},
  {title: "Didsbury", postal:" "},
  {title: "Dinas Powys", postal:" "},
  {title: "Diss", postal:" "},
  {title: "Ditton", postal:" "},
  {title: "Dollar", postal:" "},
  {title: "Doncaster", postal:" "},
  {title: "Dorchester", postal:" "},
  {title: "Dorking", postal:" "},
  {title: "Dover", postal:" "},
  {title: "Downend", postal:" "},
  {title: "Downham", postal:" "},
  {title: "Downham Market", postal:" "},
  {title: "Downpatrick", postal:" "},
  {title: "Dreghorn", postal:" "},
  {title: "Driffield", postal:" "},
  {title: "Dromore", postal:" "},
  {title: "Dudley", postal:" "},
  {title: "Duffield", postal:" "},
  {title: "Dukinfield", postal:" "},
  {title: "Dulwich", postal:" "},
  {title: "Dumbarton", postal:" "},
  {title: "Dumfries", postal:" "},
  {title: "Dunbar", postal:" "},
  {title: "Dunblane", postal:" "},
  {title: "Dundee", postal:" "},
  {title: "Dunfermline", postal:" "},
  {title: "Dungannon", postal:" "},
  {title: "Dunoon", postal:" "},
  {title: "Dunstable", postal:" "},
  {title: "Durham", postal:" "},
  {title: "Durker", postal:" "},
  {title: "Dursley", postal:" "},
  {title: "Duston", postal:" "},
  {title: "Duxford", postal:" "},
  {title: "Ealing", postal:" "},
  {title: "Earls Barton", postal:" "},
  {title: "Earlsfield", postal:" "},
  {title: "Earlsfield and Wandsworth", postal:" "},
  {title: "Easingwold", postal:" "},
  {title: "East Dulwich", postal:" "},
  {title: "East Finchley", postal:" "},
  {title: "East Ginstead", postal:" "},
  {title: "East Greenwich", postal:" "},
  {title: "East Grindstead", postal:" "},
  {title: "East Grinstead", postal:" "},
  {title: "East Ham", postal:" "},
  {title: "East Ham and Beckton", postal:" "},
  {title: "East Houses", postal:" "},
  {title: "East Kilbride", postal:" "},
  {title: "East Sheen and Mortlake", postal:" "},
  {title: "Eastbourne", postal:" "},
  {title: "Eastcote", postal:" "},
  {title: "Eastfield", postal:" "},
  {title: "Eastham", postal:" "},
  {title: "Eastleigh", postal:" "},
  {title: "Eastwood", postal:" "},
  {title: "Eaton Socon", postal:" "},
  {title: "Ebbw Vale", postal:" "},
  {title: "Eccles", postal:" "},
  {title: "Edenbridge", postal:" "},
  {title: "Edgware", postal:" "},
  {title: "Edinburgh", postal:" "},
  {title: "Edmonton", postal:" "},
  {title: "Edwalton", postal:" "},
  {title: "Egham", postal:" "},
  {title: "Egremont", postal:" "},
  {title: "Elephant &amp; Castle and Walworth", postal:" "},
  {title: "Ellesmere Port", postal:" "},
  {title: "Ellesmere, Shropshire", postal:" "},
  {title: "Elsworth", postal:" "},
  {title: "Eltham", postal:" "},
  {title: "Ely", postal:" "},
  {title: "Emsworth", postal:" "},
  {title: "Endsbury Park", postal:" "},
  {title: "Enfield", postal:" "},
  {title: "Epping", postal:" "},
  {title: "Epsom", postal:" "},
  {title: "Epworth", postal:" "},
  {title: "Erdington", postal:" "},
  {title: "Erith", postal:" "},
  {title: "Erskine", postal:" "},
  {title: "Esher", postal:" "},
  {title: "Essex", postal:" "},
  {title: "Euxton", postal:" "},
  {title: "Evesham", postal:" "},
  {title: "Ewhurst", postal:" "},
  {title: "Exeter", postal:" "},
  {title: "Exmouth", postal:" "},
  {title: "Eynsham", postal:" "},
  {title: "Fairford", postal:" "},
  {title: "Falkirk", postal:" "},
  {title: "Fallowfield", postal:" "},
  {title: "Falmouth", postal:" "},
  {title: "Fareham", postal:" "},
  {title: "Farnborough", postal:" "},
  {title: "Farnham", postal:" "},
  {title: "Farnworth", postal:" "},
  {title: "Fauldhouse", postal:" "},
  {title: "Faversham", postal:" "},
  {title: "Felinfach", postal:" "},
  {title: "Felixstowe", postal:" "},
  {title: "Feltham", postal:" "},
  {title: "Fendown", postal:" "},
  {title: "Fenstanton", postal:" "},
  {title: "Fetcham", postal:" "},
  {title: "Filby", postal:" "},
  {title: "Finchley Central", postal:" "},
  {title: "Finedon", postal:" "},
  {title: "Finsbury Park and Manor House", postal:" "},
  {title: "Flackwell Heath", postal:" "},
  {title: "Fleetwood", postal:" "},
  {title: "Flitwick", postal:" "},
  {title: "Folkestone", postal:" "},
  {title: "Fordham", postal:" "},
  {title: "Forest Gate and Upton Park", postal:" "},
  {title: "Forest Hill", postal:" "},
  {title: "Forfar", postal:" "},
  {title: "Forres", postal:" "},
  {title: "Fort William", postal:" "},
  {title: "Framlingham", postal:" "},
  {title: "Friern Barnet and New Southgate", postal:" "},
  {title: "Frilford", postal:" "},
  {title: "Frinton On Sea", postal:" "},
  {title: "Frodsham", postal:" "},
  {title: "Frome", postal:" "},
  {title: "Fulham", postal:" "},
  {title: "Fulham and Parson's Green", postal:" "},
  {title: "Fulwood", postal:" "},
  {title: "Gaerwen", postal:" "},
  {title: "Gainsborough", postal:" "},
  {title: "Galashiels", postal:" "},
  {title: "Garforth", postal:" "},
  {title: "Garstang", postal:" "},
  {title: "Gateacre", postal:" "},
  {title: "Gateshead", postal:" "},
  {title: "Gatley", postal:" "},
  {title: "Gerrards Cross", postal:" "},
  {title: "Gilberdyke", postal:" "},
  {title: "Gildersome", postal:" "},
  {title: "Gillingham", postal:" "},
  {title: "Girton", postal:" "},
  {title: "Glasgow", postal:" "},
  {title: "Glastonbury", postal:" "},
  {title: "Glenfield", postal:" "},
  {title: "Glenrothes", postal:" "},
  {title: "Glossop", postal:" "},
  {title: "Gloucester", postal:" "},
  {title: "Gloucestershire", postal:" "},
  {title: "Glynneath", postal:" "},
  {title: "Godshill", postal:" "},
  {title: "Golborne", postal:" "},
  {title: "Golders Green and Hampstead Garden Suburb", postal:" "},
  {title: "Goldthorpe", postal:" "},
  {title: "Goole", postal:" "},
  {title: "Gorleston", postal:" "},
  {title: "Gorton", postal:" "},
  {title: "Gosforth", postal:" "},
  {title: "Gosport", postal:" "},
  {title: "Gourock", postal:" "},
  {title: "Grangemouth", postal:" "},
  {title: "Grantham", postal:" "},
  {title: "Gravesend", postal:" "},
  {title: "Grays", postal:" "},
  {title: "Grayshott", postal:" "},
  {title: "Greasby", postal:" "},
  {title: "Great Barr", postal:" "},
  {title: "Great Bookham", postal:" "},
  {title: "Great Harwood", postal:" "},
  {title: "Great Malvern", postal:" "},
  {title: "Great Missenden", postal:" "},
  {title: "Great Wyrley", postal:" "},
  {title: "Great Yarmouth", postal:" "},
  {title: "Great Yeldham", postal:" "},
  {title: "Greater London", postal:" "},
  {title: "Greater Manchester", postal:" "},
  {title: "Greatstone", postal:" "},
  {title: "Greenford", postal:" "},
  {title: "Greenock", postal:" "},
  {title: "Greenwich", postal:" "},
  {title: "Greetland", postal:" "},
  {title: "Grimsby", postal:" "},
  {title: "Groby", postal:" "},
  {title: "Grove Park and Lee", postal:" "},
  {title: "Guardbridge", postal:" "},
  {title: "Guildford", postal:" "},
  {title: "Guiseley", postal:" "},
  {title: "Gwent", postal:" "},
  {title: "Hackney", postal:" "},
  {title: "Hackney and Homerton", postal:" "},
  {title: "Haddington", postal:" "},
  {title: "Hadleigh", postal:" "},
  {title: "Hailsham", postal:" "},
  {title: "Hale", postal:" "},
  {title: "Halesowen", postal:" "},
  {title: "Halesworth", postal:" "},
  {title: "Halifax", postal:" "},
  {title: "Halstead", postal:" "},
  {title: "Halton", postal:" "},
  {title: "Ham", postal:" "},
  {title: "Hambledon", postal:" "},
  {title: "Hamilton", postal:" "},
  {title: "Hammersmith", postal:" "},
  {title: "Hampstead and Swiss Cottage", postal:" "},
  {title: "Hampton Hill", postal:" "},
  {title: "Hampton Wick", postal:" "},
  {title: "Handforth", postal:" "},
  {title: "Hanwell", postal:" "},
  {title: "Hardingstone", postal:" "},
  {title: "Haringay", postal:" "},
  {title: "Harlesden, Kensal Green and Willesden", postal:" "},
  {title: "Harleston", postal:" "},
  {title: "Harlow", postal:" "},
  {title: "Harpenden", postal:" "},
  {title: "Harrogate", postal:" "},
  {title: "Harrow", postal:" "},
  {title: "Hartlepool", postal:" "},
  {title: "Hartley", postal:" "},
  {title: "Hartley Wintney", postal:" "},
  {title: "Hartshorn", postal:" "},
  {title: "Harwich", postal:" "},
  {title: "Harworth", postal:" "},
  {title: "Haslemere", postal:" "},
  {title: "Haslingdon", postal:" "},
  {title: "Haslington", postal:" "},
  {title: "Hassocks", postal:" "},
  {title: "Hastings", postal:" "},
  {title: "Hatfield", postal:" "},
  {title: "Hatfield Peverel", postal:" "},
  {title: "Hatton", postal:" "},
  {title: "Havant", postal:" "},
  {title: "Haverfordwest", postal:" "},
  {title: "Haverhill", postal:" "},
  {title: "Hawick", postal:" "},
  {title: "Haworth", postal:" "},
  {title: "Haydock", postal:" "},
  {title: "Hayes", postal:" "},
  {title: "Hayle", postal:" "},
  {title: "Hayling Island", postal:" "},
  {title: "Haywards Heath", postal:" "},
  {title: "Haywardsheath", postal:" "},
  {title: "Hazel Grove", postal:" "},
  {title: "Hazlemere", postal:" "},
  {title: "Heacham", postal:" "},
  {title: "Headcorn", postal:" "},
  {title: "Headingly", postal:" "},
  {title: "Headington", postal:" "},
  {title: "Heath Hayes", postal:" "},
  {title: "Heathfield", postal:" "},
  {title: "Heaton Chapel", postal:" "},
  {title: "Heavitree", postal:" "},
  {title: "Hedge End", postal:" "},
  {title: "Hednesford", postal:" "},
  {title: "Helensburgh", postal:" "},
  {title: "Helston", postal:" "},
  {title: "Hemel Hempstead", postal:" "},
  {title: "Hemlington", postal:" "},
  {title: "Henfield", postal:" "},
  {title: "Henley On Thames", postal:" "},
  {title: "Hensingham", postal:" "},
  {title: "Hereford", postal:" "},
  {title: "Herne Bay", postal:" "},
  {title: "Herne Hill", postal:" "},
  {title: "Hertford", postal:" "},
  {title: "Hertfordshire", postal:" "},
  {title: "Hessle", postal:" "},
  {title: "Heswall", postal:" "},
  {title: "Hexham", postal:" "},
  {title: "Heywood", postal:" "},
  {title: "High Wycombe", postal:" "},
  {title: "Higham", postal:" "},
  {title: "Highbridge", postal:" "},
  {title: "Highbury", postal:" "},
  {title: "Highcliffe On Sea", postal:" "},
  {title: "Higher Blakley", postal:" "},
  {title: "Highgate", postal:" "},
  {title: "Hillingdon", postal:" "},
  {title: "Hinchley Wood", postal:" "},
  {title: "Hinckley", postal:" "},
  {title: "Histon", postal:" "},
  {title: "Hitchin", postal:" "},
  {title: "Hoddesdon", postal:" "},
  {title: "Holbeach", postal:" "},
  {title: "Holland On Sea", postal:" "},
  {title: "Holland Park and Notting Hill", postal:" "},
  {title: "Holloway", postal:" "},
  {title: "Hollybush", postal:" "},
  {title: "Holt", postal:" "},
  {title: "Holytown", postal:" "},
  {title: "Holywell", postal:" "},
  {title: "Holywell Green, Halifax", postal:" "},
  {title: "Holywood", postal:" "},
  {title: "Honiton", postal:" "},
  {title: "Honley, Huddersfield", postal:" "},
  {title: "Hook", postal:" "},
  {title: "Horam", postal:" "},
  {title: "Horbury", postal:" "},
  {title: "Horley", postal:" "},
  {title: "Horncastle", postal:" "},
  {title: "Hornchurch", postal:" "},
  {title: "Hornsea", postal:" "},
  {title: "Horsford", postal:" "},
  {title: "Horsforth", postal:" "},
  {title: "Horsham", postal:" "},
  {title: "Horspath", postal:" "},
  {title: "Horwich", postal:" "},
  {title: "Houghton Regis", postal:" "},
  {title: "Hounslow", postal:" "},
  {title: "Hove", postal:" "},
  {title: "Hucknall", postal:" "},
  {title: "Huddersfield", postal:" "},
  {title: "Hull", postal:" "},
  {title: "Hullbridge", postal:" "},
  {title: "Hulme", postal:" "},
  {title: "Hungerford", postal:" "},
  {title: "Huntingdon", postal:" "},
  {title: "Hurstpierpoint", postal:" "},
  {title: "Hutton", postal:" "},
  {title: "Hythe", postal:" "},
  {title: "Ilford", postal:" "},
  {title: "Ilfracombe", postal:" "},
  {title: "Ilkeston", postal:" "},
  {title: "Illingworth", postal:" "},
  {title: "Immingham", postal:" "},
  {title: "Ingatestone", postal:" "},
  {title: "Ingelby Barwick", postal:" "},
  {title: "Intake", postal:" "},
  {title: "Inverness", postal:" "},
  {title: "Inverurie", postal:" "},
  {title: "Ipswich", postal:" "},
  {title: "Irlam", postal:" "},
  {title: "Irthlingborough", postal:" "},
  {title: "Irvine", postal:" "},
  {title: "Isle Of Dogs", postal:" "},
  {title: "Isle of Dogs, Millwall or Poplar", postal:" "},
  {title: "Isleworth", postal:" "},
  {title: "Iver", postal:" "},
  {title: "Ivybridge", postal:" "},
  {title: "Jarrow", postal:" "},
  {title: "Jaywick", postal:" "},
  {title: "Johnstone", postal:" "},
  {title: "Keighley", postal:" "},
  {title: "Kemsing", postal:" "},
  {title: "Kendal", postal:" "},
  {title: "Kenilworth", postal:" "},
  {title: "Kenley", postal:" "},
  {title: "Kensington", postal:" "},
  {title: "Kent", postal:" "},
  {title: "Kentish Town", postal:" "},
  {title: "Kettering", postal:" "},
  {title: "Kexbrough", postal:" "},
  {title: "Kibworth", postal:" "},
  {title: "Kidderminster", postal:" "},
  {title: "Kidlington", postal:" "},
  {title: "Kilbirnie", postal:" "},
  {title: "Kilburn", postal:" "},
  {title: "Kilburn, Queens Park and West Hampstead", postal:" "},
  {title: "Kilmarnock", postal:" "},
  {title: "Kilsyth", postal:" "},
  {title: "Kilwinning", postal:" "},
  {title: "Kimbolton", postal:" "},
  {title: "Kimnel Bay", postal:" "},
  {title: "Kings Langley", postal:" "},
  {title: "Kings Lynn", postal:" "},
  {title: "Kingsbridge", postal:" "},
  {title: "Kingsbury", postal:" "},
  {title: "Kingsteignton", postal:" "},
  {title: "Kingston", postal:" "},
  {title: "Kingston Upon Thames", postal:" "},
  {title: "Kingswinford", postal:" "},
  {title: "Kippax", postal:" "},
  {title: "Kirby Lonsdale", postal:" "},
  {title: "Kirk Sandall", postal:" "},
  {title: "Kirkby In Ashfield", postal:" "},
  {title: "Kirkcaldy", postal:" "},
  {title: "Kirkintilloch", postal:" "},
  {title: "Kirknewton", postal:" "},
  {title: "Kirton In Lindsey", postal:" "},
  {title: "Knaresborough", postal:" "},
  {title: "Knottingley", postal:" "},
  {title: "Knutton", postal:" "},
  {title: "Ladbroke Grove and North Kensington", postal:" "},
  {title: "Lambeth", postal:" "},
  {title: "Lampeter", postal:" "},
  {title: "Lanark", postal:" "},
  {title: "Lancaster", postal:" "},
  {title: "Lancing", postal:" "},
  {title: "Landore", postal:" "},
  {title: "Langley Park", postal:" "},
  {title: "Largs", postal:" "},
  {title: "Larne", postal:" "},
  {title: "Launceston", postal:" "},
  {title: "Lavenham", postal:" "},
  {title: "Leadgate", postal:" "},
  {title: "Leam Lane", postal:" "},
  {title: "Leamington Spa", postal:" "},
  {title: "Leatherhead", postal:" "},
  {title: "Leciester", postal:" "},
  {title: "Ledbury", postal:" "},
  {title: "Lee On The Solent", postal:" "},
  {title: "Leeds", postal:" "},
  {title: "Leek", postal:" "},
  {title: "Leicester", postal:" "},
  {title: "Leigh", postal:" "},
  {title: "Leigh On Sea", postal:" "},
  {title: "Leighton Buzzard", postal:" "},
  {title: "Leiston", postal:" "},
  {title: "Lenham", postal:" "},
  {title: "Leominster", postal:" "},
  {title: "Letchworth", postal:" "},
  {title: "Leven, Fife", postal:" "},
  {title: "Levenshulme", postal:" "},
  {title: "Lewes", postal:" "},
  {title: "Lewisham", postal:" "},
  {title: "Leyland", postal:" "},
  {title: "Leyton", postal:" "},
  {title: "Leytonstone", postal:" "},
  {title: "Lichfield", postal:" "},
  {title: "Lightwater", postal:" "},
  {title: "Limavady", postal:" "},
  {title: "Lincoln", postal:" "},
  {title: "Lindfield", postal:" "},
  {title: "Linlithgow", postal:" "},
  {title: "Linton - On - Ouse", postal:" "},
  {title: "Linwood", postal:" "},
  {title: "Liphook", postal:" "},
  {title: "Lisburn", postal:" "},
  {title: "Liskeard", postal:" "},
  {title: "Liss", postal:" "},
  {title: "Litherland", postal:" "},
  {title: "Little Bentley", postal:" "},
  {title: "Little Hulton", postal:" "},
  {title: "Little Lever", postal:" "},
  {title: "Little Neston", postal:" "},
  {title: "Littleborough", postal:" "},
  {title: "Littlehampton", postal:" "},
  {title: "Liverpool", postal:" "},
  {title: "Livingston", postal:" "},
  {title: "Llandaff", postal:" "},
  {title: "Llandrindod Wells", postal:" "},
  {title: "Llandudno", postal:" "},
  {title: "Llanelli", postal:" "},
  {title: "Llantwit Major", postal:" "},
  {title: "Lochgelly", postal:" "},
  {title: "Lofthouse", postal:" "},
  {title: "Londonderry", postal:" "},
  {title: "Long Crendon", postal:" "},
  {title: "Long Stratton", postal:" "},
  {title: "Longsight", postal:" "},
  {title: "Longton", postal:" "},
  {title: "Lostock Hall", postal:" "},
  {title: "Loughborough", postal:" "},
  {title: "Loughton", postal:" "},
  {title: "Louth", postal:" "},
  {title: "Lower Bradbury", postal:" "},
  {title: "Lower Edmonton", postal:" "},
  {title: "Lowestoft", postal:" "},
  {title: "Ludlow", postal:" "},
  {title: "Lurgan", postal:" "},
  {title: "Luton", postal:" "},
  {title: "Lutterworth", postal:" "},
  {title: "Lydiate", postal:" "},
  {title: "Lydney", postal:" "},
  {title: "Lymington", postal:" "},
  {title: "Lymm", postal:" "},
  {title: "Lyndhurst", postal:" "},
  {title: "Lytham", postal:" "},
  {title: "Lytham St.Annes", postal:" "},
  {title: "Macclesfield", postal:" "},
  {title: "Maesteg", postal:" "},
  {title: "Magherafelt", postal:" "},
  {title: "Maida", postal:" "},
  {title: "Maida Vale and Warwick Avenue", postal:" "},
  {title: "Maidenhead", postal:" "},
  {title: "Maidstone", postal:" "},
  {title: "Makerfield", postal:" "},
  {title: "Malden Manor", postal:" "},
  {title: "Maldon", postal:" "},
  {title: "Malton", postal:" "},
  {title: "Malvern", postal:" "},
  {title: "Manchester", postal:" "},
  {title: "Manningtree", postal:" "},
  {title: "Manor Park", postal:" "},
  {title: "Mansfield", postal:" "},
  {title: "Mansfield Woodhouse", postal:" "},
  {title: "March", postal:" "},
  {title: "Marden", postal:" "},
  {title: "Margate", postal:" "},
  {title: "Marham", postal:" "},
  {title: "Market Deeping", postal:" "},
  {title: "Market Drayton", postal:" "},
  {title: "Market Harborough", postal:" "},
  {title: "Market Rasen", postal:" "},
  {title: "Market Weighton", postal:" "},
  {title: "Marlborough", postal:" "},
  {title: "Marske-By-The-Sea", postal:" "},
  {title: "Marston", postal:" "},
  {title: "Martlesham", postal:" "},
  {title: "Marylebone, Mayfair and Soho", postal:" "},
  {title: "Maryport", postal:" "},
  {title: "Matlock", postal:" "},
  {title: "Mayland", postal:" "},
  {title: "Meanwood", postal:" "},
  {title: "Measham", postal:" "},
  {title: "Medstead", postal:" "},
  {title: "Melksham", postal:" "},
  {title: "Merthyr Tydfil", postal:" "},
  {title: "Merton and Wimbledon", postal:" "},
  {title: "Metheringham", postal:" "},
  {title: "Methven", postal:" "},
  {title: "Mexborough", postal:" "},
  {title: "Mickleover", postal:" "},
  {title: "Mickleton", postal:" "},
  {title: "Middlesbrough", postal:" "},
  {title: "Middleton", postal:" "},
  {title: "Middlewich", postal:" "},
  {title: "Midhurst", postal:" "},
  {title: "Midsomer Norton", postal:" "},
  {title: "Mile End, Stepney or Whitechapel", postal:" "},
  {title: "Milford", postal:" "},
  {title: "Milford Haven", postal:" "},
  {title: "Milford-On-Sea", postal:" "},
  {title: "Mill Hill", postal:" "},
  {title: "Millom", postal:" "},
  {title: "Milnathort", postal:" "},
  {title: "Milngavie", postal:" "},
  {title: "Milnrow", postal:" "},
  {title: "Milnthorpe", postal:" "},
  {title: "Milton Keynes", postal:" "},
  {title: "Milton, Cambridge", postal:" "},
  {title: "Minehead", postal:" "},
  {title: "Minster", postal:" "},
  {title: "Mirfield", postal:" "},
  {title: "Mitcham", postal:" "},
  {title: "Mold", postal:" "},
  {title: "Molesey", postal:" "},
  {title: "Monfieth", postal:" "},
  {title: "Monmouth", postal:" "},
  {title: "Montrose", postal:" "},
  {title: "Morden", postal:" "},
  {title: "Morecambe", postal:" "},
  {title: "Morecombe", postal:" "},
  {title: "Moreton", postal:" "},
  {title: "Moreton-In-The-Marsh", postal:" "},
  {title: "Morley", postal:" "},
  {title: "Morpeth", postal:" "},
  {title: "Mortimer", postal:" "},
  {title: "Moss Side", postal:" "},
  {title: "Mossley", postal:" "},
  {title: "Motherwell", postal:" "},
  {title: "Motspur Park", postal:" "},
  {title: "Mountain Ash", postal:" "},
  {title: "Mountsorrell", postal:" "},
  {title: "Mudford", postal:" "},
  {title: "Mumbles", postal:" "},
  {title: "Musselburgh", postal:" "},
  {title: "Muswell Hill", postal:" "},
  {title: "Nailsworth", postal:" "},
  {title: "Nairn", postal:" "},
  {title: "Nantwich", postal:" "},
  {title: "Navenby", postal:" "},
  {title: "Neath", postal:" "},
  {title: "Nelson", postal:" "},
  {title: "Netherfield", postal:" "},
  {title: "Netherton", postal:" "},
  {title: "Netley Abbey", postal:" "},
  {title: "New Bradwell", postal:" "},
  {title: "New Herrington", postal:" "},
  {title: "New Malden", postal:" "},
  {title: "New Mills", postal:" "},
  {title: "New Milton", postal:" "},
  {title: "Newark", postal:" "},
  {title: "Newark, Nottingham", postal:" "},
  {title: "Newburgh", postal:" "},
  {title: "Newbury", postal:" "},
  {title: "Newcastle", postal:" "},
  {title: "Newcastle Upon Tyne", postal:" "},
  {title: "Newcastle-Under Lyme", postal:" "},
  {title: "Newent", postal:" "},
  {title: "Newhall", postal:" "},
  {title: "Newhaven", postal:" "},
  {title: "Newmains", postal:" "},
  {title: "Newmarket", postal:" "},
  {title: "Newmills", postal:" "},
  {title: "Newport", postal:" "},
  {title: "Newport Pagnell", postal:" "},
  {title: "Newquay", postal:" "},
  {title: "Newry", postal:" "},
  {title: "Newthorpe", postal:" "},
  {title: "Newton Abbot", postal:" "},
  {title: "Newton Aycliffe", postal:" "},
  {title: "Newton Heath", postal:" "},
  {title: "Newton-Le-Willows", postal:" "},
  {title: "Newtonards", postal:" "},
  {title: "Newtonhill", postal:" "},
  {title: "Newtown", postal:" "},
  {title: "Newtownabbey", postal:" "},
  {title: "Nine Elms and South Lambeth", postal:" "},
  {title: "Norbury", postal:" "},
  {title: "Norbury and Streatham", postal:" "},
  {title: "North Berwick", postal:" "},
  {title: "North Bransholme", postal:" "},
  {title: "North Finchley and Woodside Park", postal:" "},
  {title: "North Queensferry", postal:" "},
  {title: "North Shields", postal:" "},
  {title: "North Somerset", postal:" "},
  {title: "North Walsham", postal:" "},
  {title: "Northallerton", postal:" "},
  {title: "Northampton", postal:" "},
  {title: "Northenden", postal:" "},
  {title: "Northfleet", postal:" "},
  {title: "Northolt", postal:" "},
  {title: "Northop Hall", postal:" "},
  {title: "Northowram", postal:" "},
  {title: "Northwich", postal:" "},
  {title: "Northwood", postal:" "},
  {title: "Norton", postal:" "},
  {title: "Norwich", postal:" "},
  {title: "Nottingham", postal:" "},
  {title: "Nuneaton", postal:" "},
  {title: "Nunhead", postal:" "},
  {title: "Nunhead and Peckham", postal:" "},
  {title: "Oadby", postal:" "},
  {title: "Oakham", postal:" "},
  {title: "Oban", postal:" "},
  {title: "Okehampton", postal:" "},
  {title: "Old Colwyn", postal:" "},
  {title: "Old Harlow", postal:" "},
  {title: "Oldbury", postal:" "},
  {title: "Oldham", postal:" "},
  {title: "Ollerton", postal:" "},
  {title: "Omagh", postal:" "},
  {title: "Ongar", postal:" "},
  {title: "Openshaw", postal:" "},
  {title: "Ormskirk", postal:" "},
  {title: "Orpington", postal:" "},
  {title: "Oswaldtwistle", postal:" "},
  {title: "Oswestry", postal:" "},
  {title: "Otley", postal:" "},
  {title: "Ottery St Mary", postal:" "},
  {title: "Oundle", postal:" "},
  {title: "Oxford", postal:" "},
  {title: "Oxfordshire", postal:" "},
  {title: "Oxhey", postal:" "},
  {title: "Oxted", postal:" "},
  {title: "Padiham", postal:" "},
  {title: "Paignton", postal:" "},
  {title: "Painswick", postal:" "},
  {title: "Paisley", postal:" "},
  {title: "Palmers Green", postal:" "},
  {title: "Pangbourne", postal:" "},
  {title: "Par", postal:" "},
  {title: "Parkstone", postal:" "},
  {title: "Parr, St Helens", postal:" "},
  {title: "Paulton", postal:" "},
  {title: "Peacehaven", postal:" "},
  {title: "Peckham", postal:" "},
  {title: "Peebles", postal:" "},
  {title: "Pembroke", postal:" "},
  {title: "Pembroke Dock", postal:" "},
  {title: "Pembury", postal:" "},
  {title: "Penarth", postal:" "},
  {title: "Pencoed", postal:" "},
  {title: "Penge", postal:" "},
  {title: "Penrith", postal:" "},
  {title: "Penryn", postal:" "},
  {title: "Pensfold", postal:" "},
  {title: "Pentre", postal:" "},
  {title: "Penwortham", postal:" "},
  {title: "Penzance", postal:" "},
  {title: "Perranporth", postal:" "},
  {title: "Pershore", postal:" "},
  {title: "Perth", postal:" "},
  {title: "Peterborough", postal:" "},
  {title: "Peterculter", postal:" "},
  {title: "Peterlee", postal:" "},
  {title: "Petersfield", postal:" "},
  {title: "Petts Wood", postal:" "},
  {title: "Pevensey Bay", postal:" "},
  {title: "Pewsey", postal:" "},
  {title: "Pickering", postal:" "},
  {title: "Pilgrams Hatch", postal:" "},
  {title: "Pitsea", postal:" "},
  {title: "Plaistow", postal:" "},
  {title: "Platt Bridge", postal:" "},
  {title: "Plumstead and Woolwich", postal:" "},
  {title: "Plymouth", postal:" "},
  {title: "Pocklington", postal:" "},
  {title: "Polbeth", postal:" "},
  {title: "Polegate", postal:" "},
  {title: "Polmont", postal:" "},
  {title: "Pontarddulais", postal:" "},
  {title: "Pontefract", postal:" "},
  {title: "Pontesbury", postal:" "},
  {title: "Pontypool", postal:" "},
  {title: "Pontypridd", postal:" "},
  {title: "Poole", postal:" "},
  {title: "Port Glasgow", postal:" "},
  {title: "Port Talbot", postal:" "},
  {title: "Portadown", postal:" "},
  {title: "Portchester", postal:" "},
  {title: "Porthcawl, Bridgend", postal:" "},
  {title: "Porthmadog", postal:" "},
  {title: "Portishead", postal:" "},
  {title: "Portland", postal:" "},
  {title: "Portslade Village", postal:" "},
  {title: "Portsmouth", postal:" "},
  {title: "Potters Bar", postal:" "},
  {title: "Pottersbar", postal:" "},
  {title: "Potton", postal:" "},
  {title: "Poulton-Le-Fylde", postal:" "},
  {title: "Poynton", postal:" "},
  {title: "Prescot", postal:" "},
  {title: "Prestatyn", postal:" "},
  {title: "Prestbury Village", postal:" "},
  {title: "Preston", postal:" "},
  {title: "Prestonpans", postal:" "},
  {title: "Prestwich", postal:" "},
  {title: "Prestwick", postal:" "},
  {title: "Prudhoe", postal:" "},
  {title: "Pudsey", postal:" "},
  {title: "Pulborough", postal:" "},
  {title: "Purley", postal:" "},
  {title: "Putney and Roehampton", postal:" "},
  {title: "Putney Heath", postal:" "},
  {title: "Queensbury", postal:" "},
  {title: "Queensferry", postal:" "},
  {title: "Radcliffe", postal:" "},
  {title: "Radlett", postal:" "},
  {title: "Radyr", postal:" "},
  {title: "Rainham", postal:" "},
  {title: "Rainworth", postal:" "},
  {title: "Ramsbury", postal:" "},
  {title: "Ramsey", postal:" "},
  {title: "Ramsgate", postal:" "},
  {title: "Raunds", postal:" "},
  {title: "Rawtenstall", postal:" "},
  {title: "Rayleigh", postal:" "},
  {title: "Raynes Park", postal:" "},
  {title: "Reading", postal:" "},
  {title: "Redbourn", postal:" "},
  {title: "Redcar", postal:" "},
  {title: "Redditch", postal:" "},
  {title: "Redhill", postal:" "},
  {title: "Redruth", postal:" "},
  {title: "Reigate", postal:" "},
  {title: "Renfrew", postal:" "},
  {title: "Retford", postal:" "},
  {title: "Rhos-On-Sea", postal:" "},
  {title: "Rhyl", postal:" "},
  {title: "Richmond", postal:" "},
  {title: "Rickmansworth", postal:" "},
  {title: "Riddings", postal:" "},
  {title: "Riddlesden", postal:" "},
  {title: "Ringwood", postal:" "},
  {title: "Ripley", postal:" "},
  {title: "Ripon", postal:" "},
  {title: "Rochdale", postal:" "},
  {title: "Rochester", postal:" "},
  {title: "Rochford", postal:" "},
  {title: "Roehampton", postal:" "},
  {title: "Romford", postal:" "},
  {title: "Romiley", postal:" "},
  {title: "Romsey", postal:" "},
  {title: "Rosehill", postal:" "},
  {title: "Roslin", postal:" "},
  {title: "Ross-On-Wye", postal:" "},
  {title: "Rossington", postal:" "},
  {title: "Rosyth", postal:" "},
  {title: "Rotherfield", postal:" "},
  {title: "Rotherham", postal:" "},
  {title: "Rotherhithe", postal:" "},
  {title: "Rotherhithe, South Bermondsey and Surrey Docks", postal:" "},
  {title: "Rothwell", postal:" "},
  {title: "Rottingdean", postal:" "},
  {title: "Royal Tunbridge Wells", postal:" "},
  {title: "Royal Wotton Bassett", postal:" "},
  {title: "Royston", postal:" "},
  {title: "Rubery", postal:" "},
  {title: "Rugby", postal:" "},
  {title: "Rugeley", postal:" "},
  {title: "Ruislip", postal:" "},
  {title: "Runcorn", postal:" "},
  {title: "Rushden", postal:" "},
  {title: "Rusholme", postal:" "},
  {title: "Rusthall", postal:" "},
  {title: "Rustington", postal:" "},
  {title: "Rutherglen", postal:" "},
  {title: "Ruthin", postal:" "},
  {title: "Ryde", postal:" "},
  {title: "Rye", postal:" "},
  {title: "Ryhill", postal:" "},
  {title: "Saffron Walden", postal:" "},
  {title: "Sailsbury", postal:" "},
  {title: "Sale", postal:" "},
  {title: "Salford", postal:" "},
  {title: "Salisbury", postal:" "},
  {title: "Saltash", postal:" "},
  {title: "Saltburn-By-The-Sea", postal:" "},
  {title: "Saltcoats", postal:" "},
  {title: "Sandbach", postal:" "},
  {title: "Sandhaven", postal:" "},
  {title: "Sandhurst", postal:" "},
  {title: "Sandiway", postal:" "},
  {title: "Sandown", postal:" "},
  {title: "Sandwich", postal:" "},
  {title: "Sandy", postal:" "},
  {title: "Sauchie", postal:" "},
  {title: "Saundersfoot", postal:" "},
  {title: "Sawbridgeworth", postal:" "},
  {title: "Scarborough", postal:" "},
  {title: "Scissett", postal:" "},
  {title: "Scunthorpe", postal:" "},
  {title: "Seaford", postal:" "},
  {title: "Seaham", postal:" "},
  {title: "Sealand", postal:" "},
  {title: "Seaton", postal:" "},
  {title: "Sedgley", postal:" "},
  {title: "Seer Green", postal:" "},
  {title: "Selby", postal:" "},
  {title: "Selly Park", postal:" "},
  {title: "Selsden", postal:" "},
  {title: "Selsey", postal:" "},
  {title: "Seven Sisters", postal:" "},
  {title: "Sevenoaks", postal:" "},
  {title: "Shaftsbury", postal:" "},
  {title: "Shalford", postal:" "},
  {title: "Shanklin", postal:" "},
  {title: "Sheerness", postal:" "},
  {title: "Sheffield", postal:" "},
  {title: "Sheffield Heeley", postal:" "},
  {title: "Shenfield", postal:" "},
  {title: "Shenley Church End", postal:" "},
  {title: "Shepherd's Bush", postal:" "},
  {title: "Shepperton", postal:" "},
  {title: "Shepshed", postal:" "},
  {title: "Sherborne", postal:" "},
  {title: "Sherburn In Elmet", postal:" "},
  {title: "Shildon", postal:" "},
  {title: "Shirley Croydon", postal:" "},
  {title: "Shoeburyness", postal:" "},
  {title: "Sholing", postal:" "},
  {title: "Shoreham On Sea", postal:" "},
  {title: "Shrewsbury", postal:" "},
  {title: "Sidcup", postal:" "},
  {title: "Sidmouth", postal:" "},
  {title: "Silksworth", postal:" "},
  {title: "Sittingbourne", postal:" "},
  {title: "Skegness", postal:" "},
  {title: "Skellow", postal:" "},
  {title: "Skelmersdale", postal:" "},
  {title: "Skipton", postal:" "},
  {title: "Sleaford", postal:" "},
  {title: "Slough", postal:" "},
  {title: "Small Dole", postal:" "},
  {title: "Smallfield", postal:" "},
  {title: "Snaith", postal:" "},
  {title: "Snodland", postal:" "},
  {title: "Soham", postal:" "},
  {title: "Solihul", postal:" "},
  {title: "Solihull", postal:" "},
  {title: "Somerton", postal:" "},
  {title: "South Cave", postal:" "},
  {title: "South Croydon", postal:" "},
  {title: "South Darenth", postal:" "},
  {title: "South Hetton", postal:" "},
  {title: "South Kensington", postal:" "},
  {title: "South Kirby", postal:" "},
  {title: "South Molton", postal:" "},
  {title: "South Moor", postal:" "},
  {title: "South Normanton", postal:" "},
  {title: "South Norwood", postal:" "},
  {title: "South Ockendon", postal:" "},
  {title: "South Shields", postal:" "},
  {title: "South Wimbledon", postal:" "},
  {title: "South Woodford", postal:" "},
  {title: "South Woodham", postal:" "},
  {title: "South Yardley", postal:" "},
  {title: "Southall", postal:" "},
  {title: "Southam", postal:" "},
  {title: "Southampton", postal:" "},
  {title: "Southborough", postal:" "},
  {title: "Southend", postal:" "},
  {title: "Southfields", postal:" "},
  {title: "Southgate", postal:" "},
  {title: "Southport", postal:" "},
  {title: "Southwell", postal:" "},
  {title: "Southwold", postal:" "},
  {title: "Sowerby Bridge", postal:" "},
  {title: "Spalding", postal:" "},
  {title: "Spennymoor", postal:" "},
  {title: "Spixworth", postal:" "},
  {title: "St Albans", postal:" "},
  {title: "St Austell", postal:" "},
  {title: "St Helens", postal:" "},
  {title: "St Ives", postal:" "},
  {title: "St John Woking", postal:" "},
  {title: "St John's Wood", postal:" "},
  {title: "St Leonards-On-Sea", postal:" "},
  {title: "St Marychurch", postal:" "},
  {title: "St Neots", postal:" "},
  {title: "St. Leonards On Sea", postal:" "},
  {title: "St.Helens", postal:" "},
  {title: "Stafford", postal:" "},
  {title: "Staincliffe", postal:" "},
  {title: "Staines", postal:" "},
  {title: "Stalbridge", postal:" "},
  {title: "Stamford", postal:" "},
  {title: "Stanmore", postal:" "},
  {title: "Stanwell", postal:" "},
  {title: "Stapleford", postal:" "},
  {title: "Staveley", postal:" "},
  {title: "Stenhousemuir", postal:" "},
  {title: "Stevenage", postal:" "},
  {title: "Stevenston", postal:" "},
  {title: "Stirling", postal:" "},
  {title: "Stockport", postal:" "},
  {title: "Stockton", postal:" "},
  {title: "Stockton - On -Tees", postal:" "},
  {title: "Stockton-On-Tees", postal:" "},
  {title: "Stockwood", postal:" "},
  {title: "Stoke Lodge", postal:" "},
  {title: "Stoke On Trent", postal:" "},
  {title: "Stoke Sub Hamdonn", postal:" "},
  {title: "Stoke-On-Trent", postal:" "},
  {title: "Stokeon Trent", postal:" "},
  {title: "Stone", postal:" "},
  {title: "Stonehaven", postal:" "},
  {title: "Stonehouse", postal:" "},
  {title: "Stoneleigh", postal:" "},
  {title: "Stotfold", postal:" "},
  {title: "Stourbridge", postal:" "},
  {title: "Stourport On Severn", postal:" "},
  {title: "Stowmarket", postal:" "},
  {title: "Strabane", postal:" "},
  {title: "Stranraer", postal:" "},
  {title: "Stratford", postal:" "},
  {title: "Strathaven", postal:" "},
  {title: "Streatham", postal:" "},
  {title: "Streatham Hill", postal:" "},
  {title: "Streatham Vale", postal:" "},
  {title: "Street", postal:" "},
  {title: "Streethouse", postal:" "},
  {title: "Stretford", postal:" "},
  {title: "Stretford Old Trafford", postal:" "},
  {title: "Stretham", postal:" "},
  {title: "Strood", postal:" "},
  {title: "Stroud", postal:" "},
  {title: "Studley", postal:" "},
  {title: "Sturry", postal:" "},
  {title: "Sudbury", postal:" "},
  {title: "Sunbury", postal:" "},
  {title: "Sunbury On Thames", postal:" "},
  {title: "Sunderland", postal:" "},
  {title: "Sunninghill", postal:" "},
  {title: "Surbiton", postal:" "},
  {title: "Surrey", postal:" "},
  {title: "Sutterton", postal:" "},
  {title: "Sutton", postal:" "},
  {title: "Sutton Coldfield", postal:" "},
  {title: "Sutton St James", postal:" "},
  {title: "Sutton-In-Ashfield", postal:" "},
  {title: "Swaffham", postal:" "},
  {title: "Swanage", postal:" "},
  {title: "Swanley", postal:" "},
  {title: "Swanscombe", postal:" "},
  {title: "Swansea", postal:" "},
  {title: "Swardeston", postal:" "},
  {title: "Swavesey", postal:" "},
  {title: "Swindon", postal:" "},
  {title: "Swinton", postal:" "},
  {title: "Sydenham", postal:" "},
  {title: "Syston", postal:" "},
  {title: "Tadcaster", postal:" "},
  {title: "Tadley", postal:" "},
  {title: "Tadworth", postal:" "},
  {title: "Taibach", postal:" "},
  {title: "Talbot Green", postal:" "},
  {title: "Tamworth", postal:" "},
  {title: "Tankerton", postal:" "},
  {title: "Tarleton", postal:" "},
  {title: "Taunton", postal:" "},
  {title: "Tavistock", postal:" "},
  {title: "Teignmouth", postal:" "},
  {title: "Telford", postal:" "},
  {title: "Tenbury Wells", postal:" "},
  {title: "Tenby", postal:" "},
  {title: "Tenterden", postal:" "},
  {title: "Tewkesbury", postal:" "},
  {title: "Thame", postal:" "},
  {title: "Thames Ditton", postal:" "},
  {title: "Thatcham", postal:" "},
  {title: "Thaxted", postal:" "},
  {title: "Theale", postal:" "},
  {title: "Thetford", postal:" "},
  {title: "Thirsk", postal:" "},
  {title: "Thorne", postal:" "},
  {title: "Thornhill", postal:" "},
  {title: "Thornton", postal:" "},
  {title: "Thornton Cleveleys", postal:" "},
  {title: "Thornton Heath", postal:" "},
  {title: "Thornton- Cleveleys", postal:" "},
  {title: "Thorpe Bay", postal:" "},
  {title: "Thrapston", postal:" "},
  {title: "Thurso", postal:" "},
  {title: "Ticknall", postal:" "},
  {title: "Tilbury", postal:" "},
  {title: "Tilehurst", postal:" "},
  {title: "Timperley", postal:" "},
  {title: "Tingley", postal:" "},
  {title: "Tintwistle", postal:" "},
  {title: "Tipton", postal:" "},
  {title: "Tiverton", postal:" "},
  {title: "Toddington", postal:" "},
  {title: "Todmorden", postal:" "},
  {title: "Toft", postal:" "},
  {title: "Tollsbury", postal:" "},
  {title: "Tolworth", postal:" "},
  {title: "Tonbridge", postal:" "},
  {title: "Tonteg", postal:" "},
  {title: "Tonypandy", postal:" "},
  {title: "Tonyrefail", postal:" "},
  {title: "Tooting", postal:" "},
  {title: "Torpoint", postal:" "},
  {title: "Torquay", postal:" "},
  {title: "Torrington", postal:" "},
  {title: "Totnes", postal:" "},
  {title: "Tottenham", postal:" "},
  {title: "Tottington", postal:" "},
  {title: "Totton", postal:" "},
  {title: "Towcester", postal:" "},
  {title: "Town Moor", postal:" "},
  {title: "Tranent", postal:" "},
  {title: "Trearddur Bay", postal:" "},
  {title: "Trevor", postal:" "},
  {title: "Tring", postal:" "},
  {title: "Troon", postal:" "},
  {title: "Trowbridge", postal:" "},
  {title: "Truro", postal:" "},
  {title: "Trusthorpe", postal:" "},
  {title: "Tuckton", postal:" "},
  {title: "Tulse Hill", postal:" "},
  {title: "Tulse Hill and West Norwood", postal:" "},
  {title: "Tunbridge Wells", postal:" "},
  {title: "Tutshill", postal:" "},
  {title: "Twerton", postal:" "},
  {title: "Twickenham", postal:" "},
  {title: "Tysoe", postal:" "},
  {title: "Uckfield", postal:" "},
  {title: "Uddingston", postal:" "},
  {title: "Ulverston", postal:" "},
  {title: "Upholland", postal:" "},
  {title: "Upminster", postal:" "},
  {title: "Upper Bucklebury", postal:" "},
  {title: "Uppingham", postal:" "},
  {title: "Upton Upon Severn", postal:" "},
  {title: "Urmston", postal:" "},
  {title: "Usher Moor", postal:" "},
  {title: "Uttoxeter", postal:" "},
  {title: "Uxbridge", postal:" "},
  {title: "Valentine", postal:" "},
  {title: "Ventnor", postal:" "},
  {title: "Waddington", postal:" "},
  {title: "Wadebridge", postal:" "},
  {title: "Wadworth", postal:" "},
  {title: "Wakefield", postal:" "},
  {title: "Wallasey", postal:" "},
  {title: "Wallingford", postal:" "},
  {title: "Wallington", postal:" "},
  {title: "Wallkerville", postal:" "},
  {title: "Wallsend", postal:" "},
  {title: "Walsall", postal:" "},
  {title: "Walsall Wood", postal:" "},
  {title: "Waltham Cross", postal:" "},
  {title: "Walthamstow", postal:" "},
  {title: "Walton On Thames", postal:" "},
  {title: "Walton-Le-Dale", postal:" "},
  {title: "Walworth", postal:" "},
  {title: "Wandsworth", postal:" "},
  {title: "Wapping", postal:" "},
  {title: "Warboys", postal:" "},
  {title: "Wardley Swinton", postal:" "},
  {title: "Ware", postal:" "},
  {title: "Wareham", postal:" "},
  {title: "Warminster", postal:" "},
  {title: "Warrington", postal:" "},
  {title: "Warwick", postal:" "},
  {title: "Washington", postal:" "},
  {title: "Waterloo", postal:" "},
  {title: "Waterlooville", postal:" "},
  {title: "Watford", postal:" "},
  {title: "Watlington", postal:" "},
  {title: "Watton", postal:" "},
  {title: "Weaverham", postal:" "},
  {title: "Wednesbury", postal:" "},
  {title: "Weldon", postal:" "},
  {title: "Welham Green", postal:" "},
  {title: "Wellesbourne", postal:" "},
  {title: "Welling", postal:" "},
  {title: "Wellingborough", postal:" "},
  {title: "Wellington", postal:" "},
  {title: "Wells", postal:" "},
  {title: "Welshpool", postal:" "},
  {title: "Welton", postal:" "},
  {title: "Welwyn Garden City", postal:" "},
  {title: "Wembley", postal:" "},
  {title: "Wendover", postal:" "},
  {title: "Weoley Castle", postal:" "},
  {title: "Werrington", postal:" "},
  {title: "Wesham", postal:" "},
  {title: "West Bridgford", postal:" "},
  {title: "West Brompton and World's End", postal:" "},
  {title: "West Bromwich", postal:" "},
  {title: "West Cornforth", postal:" "},
  {title: "West Drayton", postal:" "},
  {title: "West Ealing", postal:" "},
  {title: "West Ewell", postal:" "},
  {title: "West Heath", postal:" "},
  {title: "West Hendon", postal:" "},
  {title: "West Kensington", postal:" "},
  {title: "West Kirby", postal:" "},
  {title: "West Looe", postal:" "},
  {title: "West Moors", postal:" "},
  {title: "West Norwood", postal:" "},
  {title: "West Sussex", postal:" "},
  {title: "West Wellow", postal:" "},
  {title: "Westbury", postal:" "},
  {title: "Westbury On Trym", postal:" "},
  {title: "Westcliff On Sea", postal:" "},
  {title: "Western", postal:" "},
  {title: "Westhoughton", postal:" "},
  {title: "Weston Super Mare", postal:" "},
  {title: "Wetherby", postal:" "},
  {title: "Weybridge", postal:" "},
  {title: "Weybrigde", postal:" "},
  {title: "Weymouth", postal:" "},
  {title: "Whetstone", postal:" "},
  {title: "Whickham", postal:" "},
  {title: "Whipton", postal:" "},
  {title: "Whistable", postal:" "},
  {title: "Whitby", postal:" "},
  {title: "Whitchurch", postal:" "},
  {title: "Whitefield", postal:" "},
  {title: "Whitehaven", postal:" "},
  {title: "Whitley Bay", postal:" "},
  {title: "Whitstable", postal:" "},
  {title: "Whitwick", postal:" "},
  {title: "Whyteleafe", postal:" "},
  {title: "Wibsey", postal:" "},
  {title: "Wick", postal:" "},
  {title: "Wickford", postal:" "},
  {title: "Wickham", postal:" "},
  {title: "Wideopen", postal:" "},
  {title: "Widley", postal:" "},
  {title: "Widnes", postal:" "},
  {title: "Widnes, Cheshire", postal:" "},
  {title: "Wigan", postal:" "},
  {title: "Wigston", postal:" "},
  {title: "Willerby", postal:" "},
  {title: "Willersey", postal:" "},
  {title: "Willington", postal:" "},
  {title: "Wimbledon", postal:" "},
  {title: "Wincanton", postal:" "},
  {title: "Winch Wen", postal:" "},
  {title: "Winchester", postal:" "},
  {title: "Winchmore Hill", postal:" "},
  {title: "Windermere", postal:" "},
  {title: "Windlesham", postal:" "},
  {title: "Windslow", postal:" "},
  {title: "Windsor", postal:" "},
  {title: "Winlatonn", postal:" "},
  {title: "Winsford", postal:" "},
  {title: "Winterbourne", postal:" "},
  {title: "Winton", postal:" "},
  {title: "Wirksworth", postal:" "},
  {title: "Wisbech", postal:" "},
  {title: "Wishaw", postal:" "},
  {title: "Witham", postal:" "},
  {title: "Withernsea", postal:" "},
  {title: "Witney", postal:" "},
  {title: "Wiveliscombe", postal:" "},
  {title: "Wivenhoe", postal:" "},
  {title: "Woburn Sands", postal:" "},
  {title: "Woking", postal:" "},
  {title: "Wokingham", postal:" "},
  {title: "Wollaton", postal:" "},
  {title: "Wolverhampton", postal:" "},
  {title: "Wolverton", postal:" "},
  {title: "Wombourne", postal:" "},
  {title: "Wombwell", postal:" "},
  {title: "Woodbridge", postal:" "},
  {title: "Woodford Green", postal:" "},
  {title: "Woodford Halse", postal:" "},
  {title: "Woodham", postal:" "},
  {title: "Woodlands", postal:" "},
  {title: "Woodley", postal:" "},
  {title: "Woodmancote", postal:" "},
  {title: "Woodmansey", postal:" "},
  {title: "Woodstock", postal:" "},
  {title: "Woolpit", postal:" "},
  {title: "Worcester", postal:" "},
  {title: "Worcester Park", postal:" "},
  {title: "Workington", postal:" "},
  {title: "Worksop", postal:" "},
  {title: "Worsbrough", postal:" "},
  {title: "Worsley", postal:" "},
  {title: "Worthing", postal:" "},
  {title: "Wraysbury", postal:" "},
  {title: "Wrexham", postal:" "},
  {title: "Wrotham", postal:" "},
  {title: "Wyke", postal:" "},
  {title: "Wymondham", postal:" "},
  {title: "Wythenshaw", postal:" "},
  {title: "Wythenshawe", postal:" "},
  {title: "Yarm", postal:" "},
  {title: "Yateley", postal:" "},
  {title: "Yaxley", postal:" "},
  {title: "Yeadon, Leeds", postal:" "},
  {title: "Yeovil", postal:" "},
  {title: "Ynyshir", postal:" "},
  {title: "York", postal:" "},
  {title: "Ystalyfera", postal:" "},
  {title: "Ystrad Mynach", postal:" "},
]
